[global]
inputFP = '/Users/jonbrown/Documents/GitHub/Titanic-Intro-Competition/Data'
genderFN = 'gender_submission.csv'
testFN = 'test.csv'
trainFN = 'train.csv'
outputFP = '/Users/jonbrown/Documents/GitHub/Titanic-Intro-Competition/Results'

[testing]
outputFP = '/Users/jonbrown/Documents/GitHub/Titanic-Intro-Competition/tool\Test_Results'